name: dev-build

on:
  push:
    branches: [ "develop" ]

jobs:
  goreleaser:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with: 
          version: latest
          args: release -f .goreleaser.yaml --rm-dist
          workdir: ./ServerScan
      
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          path: ./ServerScan/dist/
        
